# fly.toml app configuration file generated for talkdash-private on 2023-11-12T20:46:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = "lhr"

[build]

[env]
  INSIDE_DOCKER = "true"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

# docs: https://fly.io/docs/reference/metrics/
# Not available to external traffic
[metrics]
port = 9091
path = "/metrics"
